baseurl = "https://dkraic.som.sk/"
languageCode = "en-us"
title = "Linux blog"
theme = "ghostwriter"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
Paginate = 30

[params]
  intro = true
  headline = "Linux blog"
  description = "Notes of random linux user"
  twitter = "danielkraic"
  github = "danielkraic"
  facebook = "danielkraic"
  gplus = "danielkraic"
  linkedin = "danielkraic"

[permalinks]
  post = "/:year/:month/:day/:title/"
